// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "intensity": number;
      "autoUpdateOnStartup": boolean;
      "correctArxivArticles": boolean;
      "staleMonths": number;
      "requestDelayMs": number;
      "startupDelayMs": number;
      "showStartupSummary": boolean;
      "showGraphTuningControls": boolean;
      "minimumAuthorHIndex": number;
      "apiKey": string;
    };
  }
}
